### ISSUE TITLE
Creating logs when used as library

### ISSUE THREAD

**Issue by matrixik** [evanoberholster/exiftool#3]
Hello, after https://github.com/evanoberholster/exiftool/commit/55123c71a31e6c3c4f8f0592cef0aa7ea80392cc your library started outputing logs when used as library. I think by default libraries should not generate any logs but allow users to turn it on if necessary for debugging.

**Comment by evanoberholster** [comment]
@matrixik Thanks for that suggestion. For now I removed debug logs until I can find a better way. See https://github.com/evanoberholster/exiftool/commit/6bf953ddb14a5eca00dab3725424a3221184fccc

Closing this issue.

**Comment by matrixik** [comment]
Great, thank you.
